# 부산시 건물용도 코드파일

In [56]:
import geopandas as gpd
import pandas as pd
import os

## 데이터 불러오기

- gpd_loader.py에서 get_gpd함수 가져오기
- 부산 내 16개의 구의 건물용도 .shp파일을 불러서 df로 저장하는 함수

In [ ]:
from gpd_loader import get_gpd

dir_path = '../../../Data_list/source_data/용도별건물공간확보_부산' 
자치구_list, df_dict = get_gpd(dir_path)

- 각 구이름을 key로 df는 value에 저장되어있음

In [36]:
df_dict = dict(sorted(df_dict.items()))

In [37]:
df_dict.keys()

dict_keys(['강서구', '금정구', '기장군', '남구', '동구', '동래구', '부산진구', '북구', '사상구', '사하구', '서구', '수영구', '연제구', '영도구', '중구', '해운대구'])

In [38]:
df_dict

{'강서구':              A0                            A1                   A2  \
 0      32511418  2002199031551910905200000000  2644010100101940001
 1      32491218  2002198998511910971000000000  2644010100101940008
 2      32553288  2002198987001910982000000000  2644010100101940009
 3      28657236  2006199054231910081000000000  2644010100101950004
 4      32553289  1940199003591908491200000000  2644010100101990054
 ...         ...                           ...                  ...
 24414  43618957  2006188888261763736800000000  2644011700102160010
 24415  29443316  2005188800211763684800000000  2644011700102170000
 24416  54926723  2004188792421762733000000000  2644011700102180000
 24417  29443317  2003188792831762503700000000  2644011700102180013
 24418  32250703  2004188962001761900600000000  2644011700102200004

                A3              A4 A5  A6      A7          A8 A9  ...     A27  \
 0      2644010100  부산광역시 강서구 대저1동  1  일반   194-1   103916038  1  ...      축사
 1      2644010100  부산광역시 강서구 대저1동  1  일반   194-8   103916039  1  ...  기타창고시설
 2      2644010100  부산광역시 강서구 대저1동  1  일반   194-9   103916040  1  ...     사무소
 3      2644010100  부산광역시 강서구 대저1동  1  일반   195-4   103916041  1  ...    제조업소
 4      2644010100  부산광역시 강서구 대저1동  1  일반  199-54   103916044  1  ...    단독주택
 ...           ...             ... ..  ..     ...         ... ..  ...     ...
 24414  2644011700   부산광역시 강서구 신호동  1  일반  216-10  1039132256  2  ...    유흥주점
 24415  2644011700   부산광역시 강서구 신호동  1  일반     217  1039132257  2  ...   일반음식점
 24416  2644011700   부산광역시 강서구 신호동  1  일반     218  1039132258  2  ...      의원
 24417  2644011700   부산광역시 강서구 신호동  1  일반  218-13  1039132260  2  ...      의원
 24418  2644011700   부산광역시 강서구 신호동  1  일반   220-4  1039132261  2  ...   일반음식점

       A28   A29    A30  A31  A32         A33         A34  \
 0       3  농수산용   5.40  1.0  0.0  2002-03-28  2002-06-04
 1       7    기타   5.40  1.0  NaN  2002-03-28  2002-06-04
 2       2   상업용   5.40  1.0  NaN  2002-03-28  2002-06-04
 3       2   상업용   8.20  1.0  0.0  2005-11-16  2006-03-13
 4       1   주거용   0.00  1.0  0.0        None        None
 ...    ..   ...    ...  ...  ...         ...         ...
 24414   2   상업용  24.20  7.0  1.0  2004-01-29  2006-06-27
 24415   2   상업용  20.13  5.0  1.0  2003-11-28  2005-04-19
 24416   2   상업용  18.50  5.0  1.0  2003-11-25  2004-12-27
 24417   2   상업용  15.35  4.0  1.0  2001-11-30  2003-07-10
 24418   2   상업용  20.10  5.0  1.0  2003-06-18  2004-05-28

                             A35  \
 0      2025-01-10 02:22:27.4122
 1      2025-01-10 02:22:27.4122
 2      2025-01-10 02:22:27.4122
 3      2025-01-10 02:22:27.4122
 4      2025-01-10 02:22:27.4122
 ...                         ...
 24414  2025-01-10 02:22:27.4122
 24415  2025-01-10 02:22:27.4122
 24416  2025-01-10 02:22:27.4122
 24417  2025-01-10 02:22:27.4122
 24418  2025-01-10 02:22:27.4122

                                                 geometry
 0      POLYGON ((381208.163 293218.43, 381204.375 293...
 1      POLYGON ((381143.488 293230.135, 381173.095 29...
 2      POLYGON ((381144.389 293228.515, 381149.731 29...
 3      POLYGON ((381224.563 293133.958, 381219.54 293...
 4      POLYGON ((381163.556 292975.954, 381170.73 292...
 ...                                                  ...
 24414  POLYGON ((371323.309 278301.867, 371330.098 27...
 24415  POLYGON ((371264.359 278298.667, 371264.936 27...
 24416  POLYGON ((371257.454 278189.781, 371253.614 27...
 24417  POLYGON ((371253.978 278176.27, 371254.006 278...
 24418  POLYGON ((371435.631 278101.972, 371432.797 27...

 [24419 rows x 37 columns],
 '금정구':              A0                            A1                   A2  \
 0      24482876  1973389771741938073700000000  2641010800106280091
 1      24483554  1973389774821938159200000000  2641010800106280091
 2      29560078  1976389866091934632600000000  2641010800106490025
 3      29560082  1976389868731934476300000000  2641010800106490025
 4      33872044  1997388921671944661500000000  2641010800200380025
 ...         ...                           ...                  ...
 22159  30133618  1997390594011937730300000000  2641010900105310003
 22160  34721721  1994390539001963649800000000  2641010700100810013
 22161  28234989  2003389931421931436300000000  2641010900108730014
 22162  28697150  2000390341201972510600000000  2641010700101770022
 22163  34223162  2002389793811988490300000000  2641010400109680040

                A3             A4 A5  A6      A7         A8 A9  ...  \
 0      2641010800  부산광역시 금정구 장전동  1  일반  628-91  103812155  1  ...
 1      2641010800  부산광역시 금정구 장전동  1  일반  628-91  103812156  1  ...
 2      2641010800  부산광역시 금정구 장전동  1  일반  649-25  103812167  1  ...
 3      2641010800  부산광역시 금정구 장전동  1  일반  649-25  103812168  1  ...
 4      2641010800  부산광역시 금정구 장전동  2   산   38-25  103812177  1  ...
 ...           ...            ... ..  ..     ...        ... ..  ...
 22159  2641010900  부산광역시 금정구 부곡동  1  일반   531-3  103819970  2  ...
 22160  2641010700  부산광역시 금정구 구서동  1  일반   81-13  103819980  2  ...
 22161  2641010900  부산광역시 금정구 부곡동  1  일반  873-14  103819983  2  ...
 22162  2641010700  부산광역시 금정구 구서동  1  일반  177-22  103819984  2  ...
 22163  2641010400  부산광역시 금정구 남산동  1  일반  968-40  103819986  2  ...

               A27 A28    A29    A30  A31  A32         A33         A34  \
 0             소매점   2    상업용   0.00  1.0  0.0  1973-06-05  1973-08-29
 1            단독주택   1    주거용   0.00  1.0  0.0  1973-06-05  1973-08-29
 2      기타제2종근생활시설   2    상업용   0.00  1.0  0.0  1975-12-05  1976-07-05
 3         기타종교집회장   6  문교사회용   0.00  9.0  1.0  1975-12-05  1976-07-05
 4        기타교육연구시설   6  문교사회용   9.80  4.0  1.0  1996-05-13  1997-07-02
 ...           ...  ..    ...    ...  ...  ...         ...         ...
 22159       다세대주택   1    주거용  12.50  4.0  0.0  1996-12-30  1997-10-30
 22160       다세대주택   1    주거용  15.40  4.0  0.0  1994-01-10  1994-06-23
 22161       다세대주택   1    주거용  14.15  5.0  0.0  2002-08-05  2003-01-20
 22162         아파트   1    주거용  17.50  6.0  1.0  1999-09-09  2000-01-05
 22163       다세대주택   1    주거용  14.30  5.0  0.0  2002-01-31  2002-12-20

                               A35  \
 0      2025-01-10 02:19:59.995093
 1      2025-01-10 02:19:59.995093
 2      2025-01-10 02:19:59.995093
 3      2025-01-10 02:19:59.995093
 4      2025-01-10 02:19:59.995093
 ...                           ...
 22159  2025-01-10 02:19:59.995093
 22160  2025-01-10 02:19:59.995093
 22161  2025-01-10 02:19:59.995093
 22162  2025-01-10 02:19:59.995093
 22163  2025-01-10 02:19:59.995093

                                                 geometry
 0      POLYGON ((389849.221 294116.402, 389845.1 2941...
 1      POLYGON ((389852.569 294127.525, 389850.398 29...
 2      POLYGON ((389942.581 293775.61, 389938.434 293...
 3      POLYGON ((389956.36 293768.518, 389939.167 293...
 4      POLYGON ((388996.035 294790.942, 388996.128 29...
 ...                                                  ...
 22159  POLYGON ((390670.709 294081.564, 390664.535 29...
 22160  POLYGON ((390621.243 296673.023, 390616.08 296...
 22161  POLYGON ((389998.077 293460.933, 390001.98 293...
 22162  POLYGON ((390423.67 297555.198, 390403.998 297...
 22163  POLYGON ((389875.974 299154.476, 389856.899 29...

 [22164 rows x 37 columns],
 '기장군':              A0                            A1                   A2  \
 0      31045795  2002402298371970199600000000  2671025021100010000
 1      33132973  1988402110471972351300000000  2671025021100060008
 2      33132978  1980402093411972240200000000  2671025021100060009
 3      33132983  1941402075121972058600000000  2671025021100060010
 4      28082865  1991401303931965331200000000  2671025021101120001
 ...         ...                           ...                  ...
 15713  33175235  1990403601161985302000000000  2671025922103810002
 15714  27620389  1988403583381987521800000000  2671025922104640000
 15715  27533096  1992403182931988095600000000  2671025922107670000
 15716  27533097  1992403199131988184700000000  2671025922107670000
 15717  28381438  1984403430521987509900000000  2671025922108100006

                A3                 A4 A5  A6     A7         A8 A9  ...  \
 0      2671025021  부산광역시 기장군 기장읍 동부리  1  일반      1   10431622  1  ...
 1      2671025021  부산광역시 기장군 기장읍 동부리  1  일반    6-8   10431624  1  ...
 2      2671025021  부산광역시 기장군 기장읍 동부리  1  일반    6-9   10431625  1  ...
 3      2671025021  부산광역시 기장군 기장읍 동부리  1  일반   6-10   10431626  1  ...
 4      2671025021  부산광역시 기장군 기장읍 동부리  1  일반  112-1   10431627  1  ...
 ...           ...                ... ..  ..    ...        ... ..  ...
 15713  2671025922  부산광역시 기장군 일광읍 이천리  1  일반  381-2  104319616  2  ...
 15714  2671025922  부산광역시 기장군 일광읍 이천리  1  일반    464  104319617  2  ...
 15715  2671025922  부산광역시 기장군 일광읍 이천리  1  일반    767  104319618  2  ...
 15716  2671025922  부산광역시 기장군 일광읍 이천리  1  일반    767  104319619  2  ...
 15717  2671025922  부산광역시 기장군 일광읍 이천리  1  일반  810-6  104319620  2  ...

               A27 A28    A29    A30   A31  A32         A33         A34  \
 0          기타운동시설   6  문교사회용  35.04   4.0  1.0  1999-05-18  2002-08-15
 1            단독주택   1    주거용   0.00   1.0  0.0  1987-11-07  1988-04-15
 2            단독주택   1    주거용   0.00   1.0  0.0        None        None
 3            단독주택   1    주거용   0.00   1.0  0.0        None        None
 4      기타제1종근생활시설   2    상업용  21.40   5.0  NaN  1990-11-07  1991-09-14
 ...           ...  ..    ...    ...   ...  ...         ...         ...
 15713       다세대주택   1    주거용   0.00   3.0  0.0  1989-10-14  1990-02-22
 15714        연립주택   1    주거용   0.00   3.0  1.0  1983-10-21  1988-02-24
 15715         아파트   1    주거용  40.90  15.0  1.0  1991-07-13  1992-08-24
 15716  기타제1종근생활시설   2    상업용   6.20   2.0  0.0  1991-07-13  1992-08-24
 15717        연립주택   1    주거용   0.00   3.0  0.0  1984-03-07  1984-10-11

                               A35  \
 0      2025-01-10 02:30:15.551514
 1      2025-01-10 02:30:15.551514
 2      2025-01-10 02:30:15.551514
 3      2025-01-10 02:30:15.551514
 4      2025-01-10 02:30:15.551514
 ...                           ...
 15713  2025-01-10 02:30:15.551514
 15714  2025-01-10 02:30:15.551514
 15715  2025-01-10 02:30:15.551514
 15716  2025-01-10 02:30:15.551514
 15717  2025-01-10 02:30:15.551514

                                                 geometry
 0      POLYGON ((402344.511 297388.491, 402354.576 29...
 1      POLYGON ((402186.18 297552.655, 402190.166 297...
 2      POLYGON ((402171.094 297533.872, 402165.668 29...
 3      POLYGON ((402152.839 297522.167, 402155.373 29...
 4      POLYGON ((401390.587 296850.023, 401390.699 29...
 ...                                                  ...
 15713  POLYGON ((403675.329 298848.027, 403677.132 29...
 15714  POLYGON ((403664.597 299065.362, 403663.973 29...
 15715  POLYGON ((403264.144 299136.068, 403258.038 29...
 15716  POLYGON ((403275.883 299134.184, 403273.896 29...
 15717  POLYGON ((403495.234 299073.553, 403496.845 29...

 [15718 rows x 37 columns],
 '남구':              A0                            A1                   A2  \
 0      34400680  1988391904321841988600000000  2629010600100060010
 1      34400683  1997391888761841579900000000  2629010600100060029
 2      34400688  1988391894951841895500000000  2629010600100060034
 3      28159351  1991391914351841882100000000  2629010600100060036
 4      31047117  1988391903701841821000000000  2629010600100060037
 ...         ...                           ...                  ...
 18274  27627128  1996389749051811872300000000  2629011100104980002
 18275  27627540  1992389917331819914400000000  2629011100200300019
 18276  54759809  2003391836331841916900000000  2629010600100300039
 18277  54759810  2005391862571841848700000000  2629010600100310002
 18278  54759818  2002391478631839813000000000  2629010600100560002

                A3            A4 A5  A6     A7          A8 A9  ...        A27  \
 0      2629010600  부산광역시 남구 대연동  1  일반   6-10   103413491  1  ...        소매점
 1      2629010600  부산광역시 남구 대연동  1  일반   6-29   103413496  1  ...      다가구주택
 2      2629010600  부산광역시 남구 대연동  1  일반   6-34   103413497  1  ...       단독주택
 3      2629010600  부산광역시 남구 대연동  1  일반   6-36   103413498  1  ...  제2종근린생활시설
 4      2629010600  부산광역시 남구 대연동  1  일반   6-37   103413499  1  ...       단독주택
 ...           ...           ... ..  ..    ...         ... ..  ...        ...
 18274  2629011100  부산광역시 남구 감만동  1  일반  498-2  1034134442  2  ...     생활편익시설
 18275  2629011100  부산광역시 남구 감만동  2   산  30-19  1034134518  2  ...      다세대주택
 18276  2629010600  부산광역시 남구 대연동  1  일반  30-39   103413572  2  ...       오피스텔
 18277  2629010600  부산광역시 남구 대연동  1  일반   31-2   103413576  2  ...       오피스텔
 18278  2629010600  부산광역시 남구 대연동  1  일반   56-2   103413887  2  ...      일반음식점

       A28  A29   A30  A31  A32         A33         A34  \
 0       2  상업용   0.0  5.0  1.0  1988-05-10  1988-11-17
 1       1  주거용   7.3  2.0  0.0  1997-02-17  1997-07-03
 2       1  주거용   0.0  2.0  0.0  1987-12-15  1988-02-29
 3       1  주거용   0.0  4.0  1.0  1991-11-15  1991-12-20
 4       1  주거용   0.0  2.0  0.0  1987-12-15  1988-02-29
 ...    ..  ...   ...  ...  ...         ...         ...
 18274   2  상업용   0.0  2.0  0.0  1993-12-27  1996-12-30
 18275   1  주거용  12.5  4.0  1.0  1991-08-05  1992-03-10
 18276   2  상업용  15.7  5.0  NaN  2002-08-27  2003-04-04
 18277   2  상업용  14.9  5.0  NaN  2004-12-20  2005-07-15
 18278   2  상업용  18.2  6.0  1.0  2001-12-08  2002-10-25

                             A35  \
 0      2025-01-10 02:10:31.9673
 1      2025-01-10 02:10:31.9673
 2      2025-01-10 02:10:31.9673
 3      2025-01-10 02:10:31.9673
 4      2025-01-10 02:10:31.9673
 ...                         ...
 18274  2025-01-10 02:10:31.9673
 18275  2025-01-10 02:10:31.9673
 18276  2025-01-10 02:10:31.9673
 18277  2025-01-10 02:10:31.9673
 18278  2025-01-10 02:10:31.9673

                                                 geometry
 0      POLYGON ((391983.408 284508.408, 391977.369 28...
 1      POLYGON ((391967.269 284467.322, 391956.603 28...
 2      POLYGON ((391972.255 284497.231, 391968.155 28...
 3      POLYGON ((391994.049 284496.181, 391990.052 28...
 4      POLYGON ((391974.519 284496.86, 391977.062 284...
 ...                                                  ...
 18274  POLYGON ((389827.664 281489.641, 389823.633 28...
 18275  POLYGON ((389999.233 282299.411, 389997.72 282...
 18276  POLYGON ((391915.827 284498.145, 391908.663 28...
 18277  POLYGON ((391936.3 284490.464, 391932.275 2844...
 18278  POLYGON ((391560.508 284288.922, 391549.724 28...

 [18279 rows x 37 columns],
 '동구':              A0                            A1                   A2  \
 0       3917983  0000203688601804534900000000  2617010100100320001
 1       3944998  1955203695801804437400000000  2617010100100320002
 2      27443064  1967203702471803806000000000  2617010100100350008
 3       3770175  1954203716801803863900000000  2617010100100350010
 4      31542471  1954203709541803779400000000  2617010100100350014
 ...         ...                           ...                  ...
 12506  28077445  2006204129871805489300000000  2617010100111550000
 12507  27519425  2003204034521803165900000000  2617010100111610008
 12508  28422719  1991203622381793317100000000  2617010100112030010
 12509  55017836  2003203420641793176700000000  2617010100112100006
 12510  54759836  1995204065281808493000000000  2617010200101010023

                A3            A4 A5  A6       A7         A8 A9  ...        A27  \
 0      2617010100  부산광역시 동구 초량동  1  일반     32-1   10301123  1  ...       단독주택
 1      2617010100  부산광역시 동구 초량동  1  일반     32-2   10301124  1  ...       단독주택
 2      2617010100  부산광역시 동구 초량동  1  일반     35-8   10301130  1  ...  제2종근린생활시설
 3      2617010100  부산광역시 동구 초량동  1  일반    35-10   10301132  1  ...      일반음식점
 4      2617010100  부산광역시 동구 초량동  1  일반    35-14   10301133  1  ...       단독주택
 ...           ...           ... ..  ..      ...        ... ..  ...        ...
 12506  2617010100  부산광역시 동구 초량동  1  일반     1155  103016824  2  ...        아파트
 12507  2617010100  부산광역시 동구 초량동  1  일반   1161-8  103016825  2  ...        아파트
 12508  2617010100  부산광역시 동구 초량동  1  일반  1203-10  103016826  2  ...       오피스텔
 12509  2617010100  부산광역시 동구 초량동  1  일반   1210-6  103016827  2  ...       오피스텔
 12510  2617010200  부산광역시 동구 수정동  1  일반   101-23  103017311  2  ...      다세대주택

       A28  A29    A30   A31  A32         A33         A34  \
 0       1  주거용    0.0   2.0  0.0        None        None
 1       1  주거용    0.0   2.0  0.0        None        None
 2       2  상업용   10.2   2.0  1.0        None        None
 3       2  상업용    0.0   1.0  0.0        None        None
 4       1  주거용    0.0   1.0  1.0        None        None
 ...    ..  ...    ...   ...  ...         ...         ...
 12506   1  주거용  112.4  35.0  3.0  2002-11-27  2006-01-13
 12507   1  주거용   45.3  15.0  1.0  2001-09-26  2003-09-01
 12508   2  상업용    0.0  15.0  2.0  1988-10-27  1991-05-03
 12509   2  상업용   55.5  13.0  2.0  2002-02-23  2003-11-28
 12510   1  주거용    8.4   3.0  1.0  1994-11-10  1995-02-27

                               A35  \
 0      2025-01-10 02:02:25.679991
 1      2025-01-10 02:02:25.679991
 2      2025-01-10 02:02:25.679991
 3      2025-01-10 02:02:25.679991
 4      2025-01-10 02:02:25.679991
 ...                           ...
 12506  2025-01-10 02:02:25.679991
 12507  2025-01-10 02:02:25.679991
 12508  2025-01-10 02:02:25.679991
 12509  2025-01-10 02:02:25.679991
 12510  2025-01-10 02:02:25.679991

                                                 geometry
 0      POLYGON ((386061.825 282661.149, 386053.821 28...
 1      POLYGON ((386064.421 282660.43, 386071.645 282...
 2      POLYGON ((386074.116 282600.717, 386081.254 28...
 3      POLYGON ((386089.214 282609.255, 386099.227 28...
 4      POLYGON ((386080.545 282590.519, 386083.3 2825...
 ...                                                  ...
 12506  POLYGON ((386506.198 282811.839, 386507.242 28...
 12507  POLYGON ((386390.35 282538.782, 386396.273 282...
 12508  POLYGON ((386005.45 281558.558, 386037.25 2815...
 12509  POLYGON ((385795.713 281502.689, 385814.892 28...
 12510  POLYGON ((386426.056 283078.106, 386433.105 28...

 [12511 rows x 37 columns],
 '동래구':              A0                            A1                   A2  \
 0      33136364  1987207557781903865400000000  2626010700101710001
 1      27752502  1974207642651897124700000000  2626010700102550001
 2      27752512  1966207636401897039800000000  2626010700102550001
 3      29692086  1966207620571897500900000000  2626010700102870000
 4      29692130  1966207620261897394500000000  2626010700102870000
 ...         ...                           ...                  ...
 18143  28982320  2003208395501897440500000000  2626010300100570006
 18144  28696598  1979209255701882842400000000  2626010200106290042
 18145  32151844  1996209300891895631500000000  2626010100100590010
 18146  28092542  2002206169841892442800000000  2626010800113790012
 18147  27536334  1982208348631889139900000000  2626010400101720003

                A3             A4 A5  A6       A7         A8 A9  ...    A27  \
 0      2626010700  부산광역시 동래구 명륜동  1  일반    171-1  103311866  1  ...     교회
 1      2626010700  부산광역시 동래구 명륜동  1  일반    255-1  103311874  1  ...   단독주택
 2      2626010700  부산광역시 동래구 명륜동  1  일반    255-1  103311875  1  ...   단독주택
 3      2626010700  부산광역시 동래구 명륜동  1  일반      287  103311876  1  ...   단독주택
 4      2626010700  부산광역시 동래구 명륜동  1  일반      287  103311878  1  ...   단독주택
 ...           ...            ... ..  ..      ...        ... ..  ...    ...
 18143  2626010300  부산광역시 동래구 칠산동  1  일반     57-6  103319766  2  ...  다세대주택
 18144  2626010200  부산광역시 동래구 안락동  1  일반   629-42  103319837  2  ...  다세대주택
 18145  2626010100  부산광역시 동래구 명장동  1  일반    59-10  103319849  2  ...  다세대주택
 18146  2626010800  부산광역시 동래구 온천동  1  일반  1379-12  103319957  2  ...    아파트
 18147  2626010400  부산광역시 동래구 낙민동  1  일반    172-3  103319962  2  ...    백화점

       A28    A29   A30  A31  A32         A33         A34  \
 0       6  문교사회용  24.7  5.0  1.0  1986-12-04  1987-12-31

- 원본 유지를 위해 복사본 생성

In [39]:
df_dict_copy = df_dict.copy()

In [40]:
df_dict_copy['강서구'].head(3)

,A0,A1,A2,A3,A4,A5,A6,A7,A8,A9,...,A27,A28,A29,A30,A31,A32,A33,A34,A35,geometry
0,32511418,2002199031551910905200000000,2644010100101940001,2644010100,부산광역시 강서구 대저1동,1,일반,194-1,103916038,1,...,축사,3,농수산용,5.4,1.0,0.0,2002-03-28,2002-06-04,2025-01-10 02:22:27.4122,"POLYGON ((381208.163 293218.43, 381204.375 293..."
1,32491218,2002198998511910971000000000,2644010100101940008,2644010100,부산광역시 강서구 대저1동,1,일반,194-8,103916039,1,...,기타창고시설,7,기타,5.4,1.0,NaN,2002-03-28,2002-06-04,2025-01-10 02:22:27.4122,"POLYGON ((381143.488 293230.135, 381173.095 29..."
2,32553288,2002198987001910982000000000,2644010100101940009,2644010100,부산광역시 강서구 대저1동,1,일반,194-9,103916040,1,...,사무소,2,상업용,5.4,1.0,NaN,2002-03-28,2002-06-04,2025-01-10 02:22:27.4122,"POLYGON ((381144.389 293228.515, 381149.731 29..."

## EDA

- A25:주요용도명
- A27:세부용도명
- A29:건물용도명

In [41]:
columns = ['A25' , 'A27', 'A29']

In [42]:
df_dict['강서구'][columns].head()

         A25     A27   A29
0  동.식물 관련시설      축사  농수산용
1       창고시설  기타창고시설    기타
2  제2종근린생활시설     사무소   상업용
3  제2종근린생활시설    제조업소   상업용
4       단독주택    단독주택   주거용

- 강서구를 예시로 A29, A25, A27순으로 더 세세하게 나뉨
- 그 값들을 각각 확인한다

In [43]:
print('건물용도_종류 \n: ', df_dict_copy['강서구'].A29.unique(), '\n')
print('주요용도_종류 \n: ', df_dict_copy['강서구'].A25.unique(), '\n')
print('세부용도_종류 \n: ', df_dict_copy['강서구'].A27.unique(), '\n')
print(len(df_dict_copy['강서구'].A29.unique()),'개' , len(df_dict_copy['강서구'].A25.unique()), '개', len(df_dict_copy['강서구'].A27.unique()),'개')

건물용도_종류
:  ['농수산용' '기타' '상업용' '주거용' '문교사회용' '공업용' None '공공용']

주요용도_종류
:  ['동.식물 관련시설' '창고시설' '제2종근린생활시설' '단독주택' '근린생활시설' '제1종근린생활시설' '분뇨.쓰레기처리시설'
 '교육연구및복지시설' '공장' '교육연구시설' '노유자시설' '문화및집회시설' '업무시설' '위험물저장및처리시설' None
 '공공용시설' '판매시설' '판매및영업시설' '종교시설' '운수시설' '운동시설' '숙박시설' '자동차관련시설' '의료시설'
 '공동주택' '방송통신시설' '관광휴게시설' '교정및군사시설' '제조업소' '위락시설']

세부용도_종류
:  ['축사' '기타창고시설' '사무소' '제조업소' '단독주택' '창고' '근린생활시설' '기타사무소' '기타제2종근생활시설'
 '수리점' '제2종근린생활시설' '제1종근린생활시설' '소매점' '일반음식점' '창고시설' '일반창고' '양수장'
 '기타동식물관련시설' '분뇨.쓰레기처리시설' '교육연구및복지시설' '마을공동시설' '표구점' '일반공장' '기타학교'
 '사회복지시설' '학원' '문화및집회시설' '버섯재배사' '기타일반업무시설' '기타공공시설' '업무시설' '기타위험물저장처리시설'
 '주유소' '분뇨처리시설' '휴게음식점' '다가구주택' '마을회관' None '동.식물 관련시설' '공공용시설' '일반목욕장'
 '이(미)용원' '기타제1종근생활시설' '부동산중개사무소' '기타교육연구및복지시설' '기타판매시설' '교회' '의약품도매점'
 '액화석유가스충전소' '위험물저장소' '마을공동구판장' '의원' '기타근린생활시설' '기타종교집회장' '판매및영업시설' '성당'
 '공공시설' '부화장' '도축장' '노래연습장' '고등학교' '우체국' '영유아보육시설' '유치원' '공항시설' '부동산중개업소'
 '초등학교' '승마장' '작물재배사' '기타공공용시설' '기타공공업무시설' '노인복지시설' '보건소' '공장' '자동차영업소'
 '석유판매소' '온실' '종묘배양시설' '위험물저장및처리시설' '폐기물처리시설' '전신전화국' '여인숙' '마을공동작업소'
 '기타교육연구시설' '사찰' '동사무소' '여관' '체육도장' '다중주택' '자동차관련시설' '세차장' '어린이집' '가축용창고'
 '제실' '변전소' '기타공장' '물품 제조공장' '물류터미널' '위험물제조소' '정비공장' '검사장' '폐차장'
 '기타자동차관련시설' '유해공장' '금융업소' '고시원' '연구소' '주차장' '유독물저장소' '폐기물재활용시설'
 '기타분뇨쓰레기처리시설' '종교시설' '공중화장실' '경마장' '종교집회장' '기타노유자시설' '중학교' '교육연구시설' '소방서'
 '병원' '기타전시장' '자치단체청사' '골프연습장' '파출소' '체력단련장' '기념관' '기숙사' '관망탑' '항만시설(터미널)'
 '한의원' '탁구장' '지역자치센터' '출판사' '항만시설' '정수장' '휴게소' '기타운수시설' '집배송시설' '철도시설'
 '냉동창고' '액화가스판매소' '물품 가공공장' '체육관' '테니스장' '시장' '가스배관시설' '목욕장' '통신용시설'
 '기타일반숙박시설' '다세대주택' '관리사' '교육원' '제과점' '국방·군사시설' '지구대' '기타운동시설' '미용원'
 '국가기관청사' '공원에 부수되는 시설' '관광호텔' '기원' '상점' '아파트' '오피스텔' '기타도매시장' '연립주택'
 '단란주점' '유흥주점']

8 개 30 개 168 개

> 구 이름을 변경하면서 살펴본 결과 각 구마다 건물용도 종류가 다름

- 건물용도에 해당하는 열(A25, A27, A29)에 해당하는 열만 남기고
    - 3가지 모두 None인 건물은 용도를 알 수 없으므로 drop
    - 가장 세분화된 열인 A27을 메인으로 사용함
        - 세부용도명(A27)이 None일 시, 주요용도명(A25)의 값으로 채움
        - 세부용도명(A27)과 주요용도명(A25) 모두 None일 시, 건물용도명(A29)의 값으로 채움

## 전처리

In [44]:
def fill_na(df):
    df = df.dropna(subset=columns, how='all')
    df.loc[df['A27'].isna(), 'A27'] = df.loc[df['A27'].isna(), 'A25']
    df.loc[df['A27'].isna(), 'A27'] = df.loc[df['A27'].isna(), 'A29']
    return df

- 각 구마다 적용하기 위해 for문을 사용
    - fillna()함수를 적용
    - A27, A25, A29 컬럼만 남김

In [45]:
for df_key, df in df_dict_copy.items():
    df_dict_copy[df_key] = fill_na(df)
    df_dict_copy[df_key] = df_dict_copy[df_key][columns]

- 각 구의 df에서 A27에 있는 값들을 전부 뽑아서 list화 하는데 set을 이용하여 중복을 제거

In [46]:
a27_list = list(set(val for df in df_dict_copy.values() for val in df['A27'].unique()))

- 16개 구에 해당하는 건물세부용도 이름이 전부 a27_list에 저장됐고 이를 살펴보기위해 txt파일로 변환

In [ ]:
with open('../../../Data_list/preprocessing_result/건물공간_데이터/a27_list.txt', 'w', encoding='utf-8') as f:
    for item in a27_list:
        f.write(f"{item}\n")

In [48]:
len(a27_list)

352

- 352개의 건물세부용도명을 살펴본 결과
- 학교(대학교, 고등학교 제외), 유치원, 어린이집, 노유자시설(어린이 시설이 포함되었기에), 주거용 건물 총 19개로 추려짐
- 이를 nearby_list에 저장
- 건물 선정 이유는 학교, 주거용 근처에 들락날락이 존재해야 부모님을 기다리는 시간에 편하게 방문하기 좋기 때문

In [ ]:
with open('../../../Data_list/preprocessing_result/건물공간_데이터/부산시_주거지및학교_list.txt', 'r', encoding='utf-8') as f:
    부산시_주거지및학교_list = [line.strip() for line in f.readlines()]

In [50]:
부산시_주거지및학교_list

['영유아보육시설',
 '다세대주택',
 '아동복지시설',
 '단독주택',
 '초등학교',
 '유치원',
 '주거용',
 '어린이집',
 '아파트',
 '학원',
 '중학교',
 '지역아동센터',
 '기타아동관련시설',
 '다가구주택',
 '공동주택',
 '노유자시설',
 '다중주택',
 '아동관련시설',
 '학교']

- 원본 데이터프레임에 앞서 언급한 fill_na함수를 적용 (copy본은 A25, A27, A29열만 뽑아놨으니 쓸 수 없음)
- 데이터 프레임에 A27의 값이 nearby_list에 있는 행만 남김
- 각 구별 남은 건물용도명과 어떤것들이 있는지 확인

In [51]:
for key in df_dict.keys():
    df_dict[key] = fill_na(df_dict[key])
    df_dict[key] = df_dict[key][df_dict[key]['A27'].isin(부산시_주거지및학교_list)]
    print(f'{key}의 A27 값 {len(df_dict[key].A27.unique())} \n: ',df_dict[key].A27.unique())

강서구의 A27 값 12
:  ['단독주택' '학원' '다가구주택' '영유아보육시설' '유치원' '초등학교' '다중주택' '주거용' '어린이집' '중학교'
 '다세대주택' '아파트']
금정구의 A27 값 17
:  ['단독주택' '다가구주택' '학원' '기타아동관련시설' '아동복지시설' '초등학교' '다중주택' '어린이집' '영유아보육시설'
 '유치원' '중학교' '지역아동센터' '다세대주택' '노유자시설' '공동주택' '주거용' '아파트']
기장군의 A27 값 16
:  ['단독주택' '다가구주택' '학원' '기타아동관련시설' '영유아보육시설' '초등학교' '아동복지시설' '공동주택' '어린이집'
 '지역아동센터' '유치원' '중학교' '다중주택' '다세대주택' '노유자시설' '아파트']
남구의 A27 값 15
:  ['다가구주택' '단독주택' '학원' '공동주택' '초등학교' '유치원' '중학교' '영유아보육시설' '어린이집' '기타아동관련시설'
 '노유자시설' '다중주택' '아동복지시설' '다세대주택' '아파트']
동구의 A27 값 16
:  ['단독주택' '학원' '다가구주택' '지역아동센터' '유치원' '초등학교' '중학교' '영유아보육시설' '다중주택' '공동주택'
 '어린이집' '기타아동관련시설' '아동관련시설' '다세대주택' '노유자시설' '아파트']
동래구의 A27 값 16
:  ['단독주택' '다가구주택' '기타아동관련시설' '어린이집' '초등학교' '중학교' '학원' '영유아보육시설' '유치원' '공동주택'
 '노유자시설' '지역아동센터' '다중주택' '다세대주택' '아동복지시설' '아파트']
부산진구의 A27 값 17
:  ['단독주택' '다가구주택' '학원' '초등학교' '중학교' '유치원' '기타아동관련시설' '어린이집' '아동복지시설'
 '영유아보육시설' '노유자시설' '다세대주택' '아동관련시설' '공동주택' '지역아동센터' '다중주택' '아파트']
북구의 A27 값 15
:  ['학원' '단독주택' '다가구주택' '초등학교' '중학교' '유치원' '영유아보육시설' '어린이집' '기타아동관련시설'
 '노유자시설' '지역아동센터' '공동주택' '다중주택' '다세대주택' '아파트']
사상구의 A27 값 16
:  ['단독주택' '다가구주택' '학원' '유치원' '초등학교' '중학교' '영유아보육시설' '공동주택' '노유자시설' '어린이집'
 '기타아동관련시설' '다세대주택' '아동복지시설' '다중주택' '지역아동센터' '아파트']
사하구의 A27 값 17
:  ['단독주택' '다가구주택' '다세대주택' '공동주택' '학원' '초등학교' '어린이집' '주거용' '영유아보육시설' '노유자시설'
 '기타아동관련시설' '유치원' '중학교' '다중주택' '아동복지시설' '아파트' '지역아동센터']
서구의 A27 값 17
:  ['단독주택' '다가구주택' '유치원' '학원' '초등학교' '중학교' '어린이집' '지역아동센터' '노유자시설' '영유아보육시설'
 '기타아동관련시설' '아동복지시설' '학교' '공동주택' '다중주택' '아파트' '다세대주택']
수영구의 A27 값 16
:  ['단독주택' '다가구주택' '학원' '유치원' '기타아동관련시설' '초등학교' '영유아보육시설' '노유자시설' '주거용'
 '어린이집' '공동주택' '아동복지시설' '중학교' '다세대주택' '다중주택' '아파트']
연제구의 A27 값 16
:  ['단독주택' '다가구주택' '학원' '기타아동관련시설' '중학교' '초등학교' '어린이집' '영유아보육시설' '유치원'
 '노유자시설' '공동주택' '아동복지시설' '아동관련시설' '다중주택' '다세대주택' '아파트']
영도구의 A27 값 15
:  ['단독주택' '다가구주택' '학원' '초등학교' '영유아보육시설' '어린이집' '지역아동센터' '중학교' '기타아동관련시설'
 '유치원' '공동주택' '아동복지시설' '다세대주택' '다중주택' '아파트']
중구의 A27 값 13
:  ['단독주택' '다가구주택' '학원' '기타아동관련시설' '아동복지시설' '다세대주택' '유치원' '주거용' '지역아동센터'
 '어린이집' '영유아보육시설' '다중주택' '아파트']
해운대구의 A27 값 17
:  ['단독주택' '다가구주택' '학원' '유치원' '다중주택' '아동복지시설' '기타아동관련시설' '초등학교' '영유아보육시설'
 '중학교' '어린이집' '지역아동센터' '노유자시설' '아동관련시설' '다세대주택' '아파트' '공동주택']

In [52]:
a = 0
for key in df_dict.keys():
    print(len(df_dict[key]))
    a += len(df_dict[key])
print(a)

9589
15922
8864
13782
9862
12808
17549
8220
9316
16436
9608
10417
9889
10325
3750
13921
180258

## 수정된 데이터 저장

- 각 구마다 데이터프레임을 .shp파일로 저장

In [ ]:
os.makedirs('../../../Data_list/preprocessing_result/건물공간_데이터/용도별건물공간확보_부산_가공', exist_ok=True)
for name in df_dict.keys():
    os.makedirs(f'../../../Data_list/preprocessing_result/건물공간_데이터/용도별건물공간확보_부산_가공/{name}', exist_ok=True)
    df_dict[name].to_file(f'../../../Data_list/preprocessing_result/건물공간_데이터/용도별건물공간확보_부산_가공/{name}/{name}.shp', encoding='cp949')

- 각 데이터프레임에 '자치구'라는 이름의 열을 추가
    - '자치구'열에 자치구 이름을 값으로 추가

In [54]:
for name, df in df_dict.items():
    df['자치구'] = name

- 16개의 데이터프레임을 하나의 데이터프레임으로 합침

In [57]:
df_merge = pd.concat(df_dict.values(), ignore_index=True)

- 데이터프레임의 정보를 살펴보니 위에서 각 데이터프레임의 길이를 합침 값 a와 동일한 것으로 확인

In [58]:
len(df_merge)

180258

In [59]:
df_merge.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 180258 entries, 0 to 180257
Data columns (total 38 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   A0        180258 non-null  int32
 1   A1        180258 non-null  object
 2   A2        180258 non-null  object
 3   A3        180258 non-null  object
 4   A4        180258 non-null  object
 5   A5        180258 non-null  object
 6   A6        180258 non-null  object
 7   A7        180255 non-null  object
 8   A8        180258 non-null  object
 9   A9        180258 non-null  object
 10  A10       180258 non-null  object
 11  A11       180258 non-null  object
 12  A12       180258 non-null  object
 13  A13       27519 non-null   object
 14  A14       16553 non-null   object
 15  A15       180254 non-null  object
 16  A16       180254 non-null  object
 17  A17       177268 non-null  float64
 18  A18       180000 non-null  float64
 19  A19       180255 non-null  float64
 20  A20       177121 non-null  float64
 21  A21       177178 non-null  float64
 22  A22       180169 non-null  object
 23  A23       180148 non-null  object
 24  A24       180179 non-null  object
 25  A25       180177 non-null  object
 26  A26       180252 non-null  object
 27  A27       180258 non-null  object
 28  A28       180242 non-null  object
 29  A29       180242 non-null  object
 30  A30       179525 non-null  float64
 31  A31       180192 non-null  float64
 32  A32       172960 non-null  float64
 33  A33       134157 non-null  object
 34  A34       165623 non-null  object
 35  A35       180258 non-null  object
 36  geometry  180258 non-null  geometry
 37  자치구       180258 non-null  object
dtypes: float64(8), geometry(1), int32(1), object(28)
memory usage: 51.6+ MB

- 종합한 데이터프레임을 csv파일로 저장

In [ ]:
df_merge.to_csv('../../../Data_list/preprocessing_result/건물공간_데이터/부산시_주거및학교건물데이터.csv')

## 유아시설 건물만 따로 뽑기

- 위에서 주거+학교 데이터를 뽑았음
- 이후에 유아시설만 있는 데이터가 따로 필요해 추가 가공

In [ ]:
with open('../../../Data_list/preprocessing_result/건물공간_데이터/부산_유아시설_list.txt', 'r', encoding='utf-8') as f:
    부산시_유아시설_list = [line.strip() for line in f.readlines()]

In [62]:
부산시_유아시설_list

['영유아보육시설', '아동복지시설', '초등학교', '유치원', '어린이집', '지역아동센터', '기타아동관련시설', '아동관련시설']

In [63]:
for key in df_dict.keys():
    df_dict[key] = fill_na(df_dict[key])
    df_dict[key] = df_dict[key][df_dict[key]['A27'].isin(부산시_유아시설_list)]
    print(f'{key}의 A27 값 {len(df_dict[key].A27.unique())} \n: ',df_dict[key].A27.unique())

강서구의 A27 값 4
:  ['영유아보육시설' '유치원' '초등학교' '어린이집']
금정구의 A27 값 7
:  ['기타아동관련시설' '아동복지시설' '초등학교' '어린이집' '영유아보육시설' '유치원' '지역아동센터']
기장군의 A27 값 7
:  ['기타아동관련시설' '영유아보육시설' '초등학교' '아동복지시설' '어린이집' '지역아동센터' '유치원']
남구의 A27 값 6
:  ['초등학교' '유치원' '영유아보육시설' '어린이집' '기타아동관련시설' '아동복지시설']
동구의 A27 값 7
:  ['지역아동센터' '유치원' '초등학교' '영유아보육시설' '어린이집' '기타아동관련시설' '아동관련시설']
동래구의 A27 값 7
:  ['기타아동관련시설' '어린이집' '초등학교' '영유아보육시설' '유치원' '지역아동센터' '아동복지시설']
부산진구의 A27 값 8
:  ['초등학교' '유치원' '기타아동관련시설' '어린이집' '아동복지시설' '영유아보육시설' '아동관련시설' '지역아동센터']
북구의 A27 값 6
:  ['초등학교' '유치원' '영유아보육시설' '어린이집' '기타아동관련시설' '지역아동센터']
사상구의 A27 값 7
:  ['유치원' '초등학교' '영유아보육시설' '어린이집' '기타아동관련시설' '아동복지시설' '지역아동센터']
사하구의 A27 값 7
:  ['초등학교' '어린이집' '영유아보육시설' '기타아동관련시설' '유치원' '아동복지시설' '지역아동센터']
서구의 A27 값 7
:  ['유치원' '초등학교' '어린이집' '지역아동센터' '영유아보육시설' '기타아동관련시설' '아동복지시설']
수영구의 A27 값 6
:  ['유치원' '기타아동관련시설' '초등학교' '영유아보육시설' '어린이집' '아동복지시설']
연제구의 A27 값 7
:  ['기타아동관련시설' '초등학교' '어린이집' '영유아보육시설' '유치원' '아동복지시설' '아동관련시설']
영도구의 A27 값 7
:  ['초등학교' '영유아보육시설' '어린이집' '지역아동센터' '기타아동관련시설' '유치원' '아동복지시설']
중구의 A27 값 6
:  ['기타아동관련시설' '아동복지시설' '유치원' '지역아동센터' '어린이집' '영유아보육시설']
해운대구의 A27 값 8
:  ['유치원' '아동복지시설' '기타아동관련시설' '초등학교' '영유아보육시설' '어린이집' '지역아동센터' '아동관련시설']

In [64]:
a = 0
for key in df_dict.keys():
    print(len(df_dict[key]))
    a += len(df_dict[key])
print(a)

55
82
98
106
56
101
102
111
70
153
58
52
62
78
11
130
1325

In [ ]:
os.makedirs('../../../Data_list/preprocessing_result/건물공간_데이터/용도별건물공간확보_부산_가공', exist_ok=True)

In [66]:
for name, df in df_dict.items():
    df['자치구'] = name

In [67]:
df_merge2 = pd.concat(df_dict.values(), ignore_index=True)

In [68]:
len(df_merge2)

1325

In [69]:
gdf = gpd.GeoDataFrame(df_merge2, geometry=df_merge2['geometry'])

In [ ]:
os.makedirs('../../../Data_list/preprocessing_result/건물공간_데이터/부산시_유아시설', exist_ok=True)

In [ ]:
gdf.to_file('../../../Data_list/preprocessing_result/건물공간_데이터/부산시_유아시설/부산시_유아시설_gdf.shp', encoding='cp949')